// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQzlWer3kLDZBVOOOekGobbcaY51JlWFE',
    appId: '1:329609266595:web:f697d5015346f19d360616',
    messagingSenderId: '329609266595',
    projectId: 'baytley-properties',
    authDomain: 'baytley-properties.firebaseapp.com',
    storageBucket: 'baytley-properties.firebasestorage.app',
    measurementId: 'G-4BHSWBB2VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXc2bL7NKVN_JwWn8DG0jNZWygdtrcf4I',
    appId: '1:329609266595:android:b3d3b5ff54089b37360616',
    messagingSenderId: '329609266595',
    projectId: 'baytley-properties',
    storageBucket: 'baytley-properties.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTp2ShxXeitFpqsEGhRFxqKBVXu6pSKpQ',
    appId: '1:329609266595:ios:0e76dad726367dde360616',
    messagingSenderId: '329609266595',
    projectId: 'baytley-properties',
    storageBucket: 'baytley-properties.firebasestorage.app',
    iosClientId: '329609266595-12ct9bl2uke2s30ktomf393vstc2obbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.baytley',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTp2ShxXeitFpqsEGhRFxqKBVXu6pSKpQ',
    appId: '1:329609266595:ios:0e76dad726367dde360616',
    messagingSenderId: '329609266595',
    projectId: 'baytley-properties',
    storageBucket: 'baytley-properties.firebasestorage.app',
    iosClientId: '329609266595-12ct9bl2uke2s30ktomf393vstc2obbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.baytley',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQzlWer3kLDZBVOOOekGobbcaY51JlWFE',
    appId: '1:329609266595:web:b2006ccee2cd684c360616',
    messagingSenderId: '329609266595',
    projectId: 'baytley-properties',
    authDomain: 'baytley-properties.firebaseapp.com',
    storageBucket: 'baytley-properties.firebasestorage.app',
    measurementId: 'G-TRD49YW634',
  );
}
